### ISSUE TITLE
Cannot get Gamertag information 

### ISSUE THREAD

**Issue by BAG-OF-CHIPS-XX** [joealcorn/xbox#10]
This has been working up until 1/12/19. see below for issue.

Traceback (most recent call last):
  File "C:\Users\cdang\Desktop\test.py", line 7, in <module>
    gametag = xbox.GamerProfile.from_gamertag(gt)
  File "C:\Python27\lib\site-packages\xbox\resource.py", line 67, in from_gamertag
    return cls._fetch(url)
  File "C:\Python27\lib\site-packages\xbox\decorators.py", line 8, in inner
    return func(*a, **kw)
  File "C:\Python27\lib\site-packages\xbox\resource.py", line 118, in _fetch
    raw_json = resp.json()
  File "C:\Python27\lib\site-packages\xbox\vendor\requests\models.py", line 771, in json
    return json.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by BAG-OF-CHIPS-XX** [comment]
This may be an issue with xbox live, it seems to be having issue right now:

https://support.xbox.com/en-US/xbox-live-status
